### PR TITLE
bugfix: non-ascii chars in dpkg log file crashes unattended upgrades

### PR DESCRIPTION
**Pull request by cletomartin**
This is a minor tweak that I think fix this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812857

### CODE REVIEW

**Comment by lafrech** [comment]
Travis check failed because of `encoding`, which is Python 3 only. More info about this here: http://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2.

Travis tests for both Python 2 and 3.

    # test with both py2 and py3 for now and also use coverage for the py2

I'm wondering about the need to support Python2. Is there a platform targetted by `unattended-upgrades` that still does not have Python 3?

**Comment by GhostLyrics** [comment]
As long as potential backports to `precise` might be necessary, probably yes. Afair the UU package depends on Python 2 there. Not entirely sure about `trusty`.

**Comment by cletomartin** [comment]
Thanks for the feedback! I guess I can use `io.open` instead then, right? https://docs.python.org/2/library/io.html#io.open

**Comment by mvo5** [comment]
Hey @cletomartin - nice to see you. Thanks for the branch.

**Pull request merged**
