### PR TITLE
Replace boolean Unattended-Upgrade::MailOnlyOnError mailing report op…

### PR DESCRIPTION
**Pull request by original-birdman**
…tion with multi-valued (string) Unattended-Upgrade::MailReport.

### CODE REVIEW

**Comment by original-birdman** [comment]
I've updated `test/aptroot/etc/apt/apt.conf.d/50unattended-upgrades` with the new option, but haven't changed any of the `50unattended-upgrades.*` files in `data/` as I'm not sure who "owns" them.

**Comment by rbalint** [comment]
@original-birdman Files in `data/` are maintained here for the benefit of the derivative distros. Please update the configuration files, too.

**Comment by original-birdman** [comment]
Re-doing with `data/` files modified as well.

**Comment by rbalint** [comment]
You can just force-push to your branch to get the existing PRs updated, there is no need to open new ones.

**Pull request closed without merging**
