### PR TITLE
Add webhook support

### PR DESCRIPTION
**Pull request by papamoose**
I've added webhook support. Most of the testing was done sending to Discord and a local python webserver that displays whatever is in POST.

- Used `def send_summary_mail()` as a guide.
- left out sending dpkg_log and mem_log.
  - The variables still get passed around, but don't get used.
- The json data structure should be given a second look before it becomes permanent.
- 2000 character limit for no other reason than that is what Discord's limit is. If it's over 2000, I overwrite the 'package' key saying it's too long to include and send the notification anyways.
- I'm currently testing this code on some of my personal servers. Maybe others can test as well.
- This uses `python3-requests`, so the package would grow a dependency. Maybe `urllib` should be used instead.

The goal is to provide data to web server that can ingest JSON and then do something smart with it.

TODO: Can someone write test code for this or help me write it?

Let me know what you think.

Sample output in Discord:

```
Spidey Bot
BOT
 — Today at 3:59 PM
{"hostname": "zeus.example.com", "reboot_flag": true, "hold_flag": false, "result": "SUCCESS", "packages": {}}
```

```
Spidey Bot
BOT
 — Today at 4:13 PM
{"hostname": "zeus.example.com", "reboot_flag": true, "hold_flag": false, "result": "SUCCESS", "packages": {"upgraded": ["alsa-ucm-conf", "cloud-init", "libdrm-common", "libdrm2", "libnetplan0", "libnss-systemd", "libpam-modules", "libpam-modules-bin", "libpam-runtime", "libpam-systemd", "libpam0g", "libprocps8", "libsystemd0", "libudev1", "libudisks2-0", "linux-firmware", "netplan.io", "open-vm-tools", "procps", "python-apt-common", "python3-apt", "python3-update-manager", "snapd", "systemd", "systemd-sysv", "systemd-timesyncd", "thermald", "udev", "udisks2", "update-manager-core"]}}
```
After piping to `jq`:
```
{
  "hostname": "zeus.example.com",
  "reboot_flag": true,
  "hold_flag": false,
  "result": "SUCCESS",
  "packages": {
    "upgraded": [
      "alsa-ucm-conf",
      "cloud-init",
      "libdrm-common",
      "libdrm2",
      "libnetplan0",
      "libnss-systemd",
      "libpam-modules",
      "libpam-modules-bin",
      "libpam-runtime",
      "libpam-systemd",
      "libpam0g",
      "libprocps8",
      "libsystemd0",
      "libudev1",
      "libudisks2-0",
      "linux-firmware",
      "netplan.io",
      "open-vm-tools",
      "procps",
      "python-apt-common",
      "python3-apt",
      "python3-update-manager",
      "snapd",
      "systemd",
      "systemd-sysv",
      "systemd-timesyncd",
      "thermald",
      "udev",
      "udisks2",
      "update-manager-core"
    ]
  }
}
```

### CODE REVIEW

**Comment by papamoose** [comment]
@mvo5 I think using `urllib.requests` from python standard lib is do-able and probably a good idea to eliminate the extra dependency. I'll update the patch accordingly.

Re [1]: "Python 2 is unsupported by the Python Foundation since 2020-01-01 and is being removed as of Debian 11 (Bullseye)." https://wiki.debian.org/Python; https://www.python.org/doc/sunset-python-2/
At least on my Ubuntu system the `u-u` script specifies `#!/usr/bin/python3` specifically. Maybe you can provide context I don't have, but it seems python2 support might be unnecessary.

**Comment by simon-ourmachinery** [comment]
What is needed to make them be able to push to master? @mvo5 @papamoose

I kind of need this since I wanted to integrate this into our slack communication.

**Comment by simon-ourmachinery** [comment]
I would really like this to be in there.

**Comment by papamoose** [comment]
Closing in favor of re-implementation in #325.

**Pull request closed without merging**
