### PR TITLE
check if user is logged in before reboot

### PR DESCRIPTION
**Pull request by a-detiste**
other wishlist/low priority stuff

### CODE REVIEW

**Comment by mvo5** [comment]
Hey Alexandre, thanks a lot for this branch and sorry that it took me forever to merge it :/ Its great, I fixed up the translation issue you mentioned in e1b826b by just using ngettext(). Its 233de95 if you want to to review the change(s). Thanks again and this feature will be part of the next upload.

**Comment by a-detiste** [comment]
Thank you very much for the review, it's allways nice learning new tricks like `ngettext()`.  
I'd like to review this and also #6 .

**Comment by mvo5** [comment]
Hey! I am working on #6 right now, it looks great, I just want to see if I can extract some common code from do_install and add some tests. Let me know please if you notice anything in further review or testing for this branch or #6. I'm also available on irc in e.g. #debian-apt on OFTC for quick turnaround.

**Comment by a-detiste** [comment]
Ok, I'll have a look at this... I find funny that this work on UU got interrupted by a dumb WinXP nag screen... now I'll have to wait 1/2h for a reboot.

xp

**Comment by mvo5** [comment]
On Tue, May 26, 2015 at 01:34:53AM -0700, Alexandre Detiste wrote:
> Ok, I'll have a look at this... I find funny that this work on UU got interrupted by a dumb WinXP nag screen... now I'll have to wait 1/2h for a reboot.
> 
> xp

Hehe :)

**Comment by a-detiste** [comment]
I created a new P.R. #8 with a little tweak, for the rest this seems fine.

**Comment by mvo5** [comment]
@a-detiste thanks! I merged this into master and it looks like its time for a new release with the nice new features that you and Alexander did :) Unless you notice anything in master that is not quite right I would like to release a new version this week.

**Comment by a-detiste** [comment]
I found a problem in the build itself (PR #9) that was never triggered before because the `all` packages are not rebuilt, they are taken as-is in the archive, and you happen to have the python*-mock modules installed.

---

I can provide updated french translation, maybe you need to refresh the .pot file first.

**Comment by a-detiste** [comment]
It works perfectly, `libqtgstreamerutils-0.10-0`that has been deprecated for years has be auto-removed today :smile:

**Comment by mvo5** [comment]
Yay! Great to hear :)

**Pull request merged**
